### ISSUE TITLE
Add JDA Types 

### ISSUE THREAD

**Issue by Koboo** [Rollczi/LiteDevelopers-docs#39]
Hey there, 
since this project doesn't have any CONTRIBUTING.md, I'm doing this by feeling. :)

I tried using LiteCommands with JDA. It's extremley simple to "install and use", but there's documentation about the supported types.

I'm not really familiar with the code-base of LiteCommands itself, but I will try to add the argument types I could find into a PR. 

Please let me know, if I missed any argument types. 

After I created the PR, I will link it here.

Another question is, if it would be possible to documentate the default `@Context` bindable arguments like the `SlashCommandInteractionEvent` or the `MessageChannelUnion`?

Best regards

Edit: 
Created the PR https://github.com/Rollczi/LiteDevelopers-docs/pull/40

**Comment by Rollczi** [comment]
> Another question is, if it would be possible to documentate the default `@Context` bindable arguments like the `SlashCommandInteractionEvent` or the `MessageChannelUnion`?
> 

Hi @Koboo,
Yeah there is not problem with this, it will be very helpful for other developers.
